spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/fraud_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

app:
  ml-service:
    base-url: ${ML_SERVICE_BASE_URL:http://ml-service:8000}
